/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizQuizIdIndexRouteImport } from './routes/quiz.$quizId.index'
import { Route as QuizQuizIdChapterIdRouteImport } from './routes/quiz.$quizId.$chapterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdIndexRoute = QuizQuizIdIndexRouteImport.update({
  id: '/quiz/$quizId/',
  path: '/quiz/$quizId/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdChapterIdRoute = QuizQuizIdChapterIdRouteImport.update({
  id: '/quiz/$quizId/$chapterId',
  path: '/quiz/$quizId/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz/$quizId/$chapterId': typeof QuizQuizIdChapterIdRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz/$quizId/$chapterId': typeof QuizQuizIdChapterIdRoute
  '/quiz/$quizId': typeof QuizQuizIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz/$quizId/$chapterId': typeof QuizQuizIdChapterIdRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz/$quizId/$chapterId' | '/quiz/$quizId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz/$quizId/$chapterId' | '/quiz/$quizId'
  id: '__root__' | '/' | '/quiz/$quizId/$chapterId' | '/quiz/$quizId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizQuizIdChapterIdRoute: typeof QuizQuizIdChapterIdRoute
  QuizQuizIdIndexRoute: typeof QuizQuizIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/': {
      id: '/quiz/$quizId/'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof QuizQuizIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/$chapterId': {
      id: '/quiz/$quizId/$chapterId'
      path: '/quiz/$quizId/$chapterId'
      fullPath: '/quiz/$quizId/$chapterId'
      preLoaderRoute: typeof QuizQuizIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizQuizIdChapterIdRoute: QuizQuizIdChapterIdRoute,
  QuizQuizIdIndexRoute: QuizQuizIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
